### ISSUE TITLE
网页端导航栏显示不全

### ISSUE THREAD

**Issue by HLXY-420** [Open-BJUT/BJUT-Helper#9]
页面宽度大于1218px时，导航栏变为横置，如下图，此时“电路分析基础”及之后的内容会变得不可见，如下图：
![image](https://github.com/Open-BJUT/BJUT-Helper/assets/73209424/ad98bfac-fea0-427e-b7b7-c36ccf37aa64)
![image](https://github.com/Open-BJUT/BJUT-Helper/assets/73209424/fd09a1b8-b78b-49d8-b3fc-cf20a56582fa)

**Comment by Nagi-ovo** [comment]
thx for the issue !
已更改导航栏样式~

**Comment by Nagi-ovo** [comment]
Subit欸，我是21格物的张泽西，同学你是哪一届的呀😊

**Comment by HLXY-420** [comment]
我是23致知的刘宇宸，SubIT23届社长（

**Comment by Nagi-ovo** [comment]
👌，你现在是来BJUT了嘛，啥专业呀:)

**Comment by HLXY-420** [comment]
是啊，~~来找老社长了~~，在计科

**Comment by Nagi-ovo** [comment]
不错hhh，咱俩加个v吧，zzhang32qq
